openapi: 3.0.3
info:
  title: API de Gestion des Utilisateurs
  description: API pour gérer les utilisateurs avec pagination
  version: 1.0.0
paths:
  /users:
    get:
      summary: Récupère une liste d'utilisateurs
      description: Récupère une liste d'utilisateurs avec pagination en utilisant les paramètres page et size
      operationId: getUsers
      parameters:
        - name: page
          in: query
          description: Numéro de la page à récupérer
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: size
          in: query
          description: Nombre d'utilisateurs par page
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
      responses:
        '200':
          description: Liste des utilisateurs récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: Tamby
                    email:
                      type: string
                      example: Tamby@gmail.com
                  required:
                    - id
                    - name
                    - email