openapi: 3.0.3
info:
  title: API de Gestion de Produits et Commandes
  description: API pour gérer les produits et les commandes avec pagination et authentification
  version: 1.0.0
components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
          description: Nom du produit
          example: Pomme
        expiration_datetime:
          type: string
          format: date-time
          description: Date et heure d'expiration du produit
          example: 2025-12-31T23:59:59Z
        price:
          type: number
          format: float
          description: Prix du produit
          example: 1.99
      required:
        - name
        - expiration_datetime
        - price
    Order:
      type: object
      properties:
        identifier:
          type: integer
          description: Identifiant unique de la commande
          example: 101
        customer_name:
          type: string
          description: Nom du client
          example: Alice Dupont
        creation_datetime:
          type: string
          format: date-time
          description: Date et heure de création de la commande
          example: 2025-08-22T12:30:00Z
        total_amount:
          type: number
          format: float
          description: Montant total de la commande
          example: 25.47
      required:
        - identifier
        - customer_name
        - creation_datetime
        - total_amount
  parameters:
    PageParam:
      name: page
      in: query
      description: Numéro de la page à récupérer
      required: false
      schema:
        type: integer
        minimum: 1
        default: 1
      example: 1
    SizeParam:
      name: size
      in: query
      description: Nombre d'éléments par page
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20
      example: 20
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
      description: Authentification basique avec nom d'utilisateur et mot de passe
security:
  - BasicAuth: []      
paths:
  /products:
    get:
      tags:
        - Products
      summary: Recherche une liste de produits
      description: Récupère une liste de produits avec pagination et recherche par terme
      operationId: getProducts
      parameters:
        - $ref: '#/components/parameters/PageParam'
        - $ref: '#/components/parameters/SizeParam'
        - name: q
          in: query
          description: Terme de recherche pour filtrer les produits
          required: false
          schema:
            type: string
          example: pomme
      responses:
        '200':
          description: Liste des produits récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              examples:
                multipleProducts:
                  summary: Liste avec plusieurs produits
                  value:
                    - name: Pomme
                      expiration_datetime: 2025-12-31T23:59:59Z
                      price: 1.99
                    - name: Banane
                      expiration_datetime: 2025-11-30T23:59:59Z
                      price: 2.49
                emptyList:
                  summary: Liste vide
                  value: []